import type { ComponentType } from "react";
import {
  AIOSText,
  AIOSButton,
  AIOSCard,
  AIOSRow,
  AIOSColumn,
  AIOSDivider,
  AIOSTabs,
  AIOSImage,
  AIOSIcon,
  AIOSList,
  AIOSStockTicker,
  AIOSStockAlert,
  AIOSEmailRow,
  AIOSMetricCard,
  AIOSSparklineChart,
  AIOSCalendarEvent,
  AIOSClock,
  AIOSStockWatchlist,
  AIOSFileExplorer,
  AIOSFileViewer,
  AIOSFileRow,
  AIOSFallback,
} from "./aios";

export const componentMap: Record<string, ComponentType<any>> = {
  Text: AIOSText,
  Button: AIOSButton,
  Card: AIOSCard,
  Row: AIOSRow,
  Column: AIOSColumn,
  Divider: AIOSDivider,
  Tabs: AIOSTabs,
  Image: AIOSImage,
  Icon: AIOSIcon,
  List: AIOSList,
  // Custom Astra components
  StockTicker: AIOSStockTicker,
  StockAlert: AIOSStockAlert,
  StockWatchlist: AIOSStockWatchlist,
  EmailRow: AIOSEmailRow,
  MetricCard: AIOSMetricCard,
  SparklineChart: AIOSSparklineChart,
  CalendarEvent: AIOSCalendarEvent,
  Clock: AIOSClock,
  FileExplorer: AIOSFileExplorer,
  FileViewer: AIOSFileViewer,
  FileRow: AIOSFileRow,
};

export const fallbackComponent = AIOSFallback;
